### ISSUE TITLE
App is not installed if source is not main.f90

### ISSUE THREAD

**Issue by aradi** [fortran-lang/fpm#1033]
### Description

I have created a [generic cookiecutter template for Fortran projects](https://github.com/fortuno-repos/cookiecutter-fortran-project) offering various modern build systems as option, among others also fpm. When trying to get the same repository layout for all build systems, which differs slightly from fpm's default layout, I stumbled about a strange behavior upon app installation:

* If the app source is `main.f90`, everything works as expected, app installed.
* If the app source is something else (e.g. `myapp.f90`), an error is raised upon installation (`<ERROR> Project does not contain any installable targets`)
* Strange enough, if there are two programs in the app folder and one of them is in `main.f90`, then both apps are installed.

```
fpm new test
cd test
mv app/main.f90 app/myapp.f90
fpm build
fpm install --prefix $PWD/_install
```

### Expected Behaviour

The code above should install the program `myapp` into `_install/bin`

### Version of fpm

0.10.1

### Platform and Architecture

Linux

### Additional Information

My current workaround is to specify `name` and `main` for `myapp` in the `[[executable]]` section, but in my opinion, it should work without it out of the box.

**Comment by perazz** [comment]
Thank you for reporting this @aradi. You're stumbling upon the fact that the default `auto-executables` option, really has always been searching for a `main.f90` rather than "any program definitions", like [is reported in the documentation](https://fpm.fortran-lang.org/spec/manifest.html?highlight=auto%20executables#automatic-target-discovery): 

https://github.com/fortran-lang/fpm/blob/88ebb0adec1566b324616f5adcd13a51359245a0/src/fpm/manifest.f90#L45-L58
