### ISSUE TITLE
fpm test with --runner

### ISSUE THREAD

**Issue by jacobwilliams** [fortran-lang/fpm#1041]
### Description

To run all the tests, you can do this:

`fpm test`

However, the `--runner` arg doesn't seem to work in this mode:

`fpm test --runner "time"`

It prints "Available names:" and then lists all the tests. So, it only seems to work when you manually specify a test to use the runner:

`fpm test blah --runner "time"`

It would be nice if `fpm test --runner ...` worked too. The intent is to use the runner to run all the tests.

### Possible Solution

Add support for `fpm test --runner ...` to run all the tests.

### Additional Information

Version:     0.10.0, alpha

**Comment by lockstockandbarrel** [comment]
fpm(1) should (and did in previous versions) default to running all
tests but as a work-around if you use globbing to specify all the test
names or the special name ...  which does not appear to be currently
documented all the tests will run:

Assuming you are using the GNU/Linux time(1) command

```bash
#!/bin/bash

rm -f time.log 
export TIME='%C@user@%U@system@%S@elapsed@%e@CPU@%P'
fpm test --runner  '/bin/time --output time.log --append' '*'
column -t -s '@' time.log|sort -k 7h |tee elapsed.log
rm -f time.log

export TIME='%C: %Uuser %Ssystem %Eelapsed %PCPU (%Xtext+%Ddata %Mmax)k %Iinputs+%Ooutputs (%Fmajor+%Rminor)pagefaults %Wswaps'
fpm test --runner  '2>&1 /bin/time' '*'|tee alltime.log
```
### elapsed.log
```text
build/gfortran_E167FD2A985B468F/test/cblat1_a  user  0.00  system  0.00  elapsed  0.00  CPU  100%
build/gfortran_E167FD2A985B468F/test/cblat1    user  0.00  system  0.00  elapsed  0.00  CPU  100%
build/gfortran_E167FD2A985B468F/test/dblat1_a  user  0.00  system  0.00  elapsed  0.00  CPU  50%
build/gfortran_E167FD2A985B468F/test/dblat1    user  0.00  system  0.00  elapsed  0.00  CPU  50%
build/gfortran_E167FD2A985B468F/test/sblat1_a  user  0.00  system  0.00  elapsed  0.00  CPU  33%
build/gfortran_E167FD2A985B468F/test/sblat1    user  0.00  system  0.00  elapsed  0.00  CPU  50%
build/gfortran_E167FD2A985B468F/test/zblat1_a  user  0.00  system  0.00  elapsed  0.00  CPU  100%
build/gfortran_E167FD2A985B468F/test/zblat1    user  0.00  system  0.00  elapsed  0.00  CPU  33%
build/gfortran_E167FD2A985B468F/test/dblat2_a  user  0.05  system  0.00  elapsed  0.06  CPU  98%
build/gfortran_E167FD2A985B468F/test/sblat2    user  0.05  system  0.00  elapsed  0.06  CPU  98%
build/gfortran_E167FD2A985B468F/test/zblat2_a  user  0.08  system  0.00  elapsed  0.08  CPU  97%
build/gfortran_E167FD2A985B468F/test/dblat2    user  0.08  system  0.00  elapsed  0.09  CPU  98%
build/gfortran_E167FD2A985B468F/test/sblat2_a  user  0.08  system  0.00  elapsed  0.09  CPU  98%
build/gfortran_E167FD2A985B468F/test/cblat2_a  user  0.10  system  0.00  elapsed  0.10  CPU  100%
build/gfortran_E167FD2A985B468F/test/sblat3    user  0.10  system  0.00  elapsed  0.10  CPU  98%
build/gfortran_E167FD2A985B468F/test/cblat2    user  0.11  system  0.00  elapsed  0.11  CPU  100%
build/gfortran_E167FD2A985B468F/test/zblat2    user  0.11  system  0.00  elapsed  0.11  CPU  98%
buid/gfortran_E167FD2A985B468F/test/dblat3_a  user  0.14  system  0.00  elapsed  0.14  CPU  98%
build/gfortran_E167FD2A985B468F/test/sblat3_a  user  0.13  system  0.00  elapsed  0.14  CPU  98%
build/gfortran_E167FD2A985B468F/test/dblat3    user  0.15  system  0.00  elapsed  0.16  CPU  98%
build/gfortran_E167FD2A985B468F/test/cblat3_a  user  0.18  system  0.00  elapsed  0.18  CPU  98%
build/gfortran_E167FD2A985B468F/test/cblat3    user  0.18  system  0.00  elapsed  0.18  CPU  98%
build/gfortran_E167FD2A985B468F/test/zblat3    user  0.20  system  0.00  elapsed  0.20  CPU  99%
build/gfortran_E167FD2A985B468F/test/zblat3_a  user  0.20  system  0.00  elapsed  0.21  CPU  98%
```
so `fpm test --runner time ...` should work in the meantime.  GNU/Linux users might find the examples of sending timeing information to a separate file or including the results sequentially in stdout useful as well.

**Comment by perazz** [comment]
This behavior was introduced in b406adf and is still there.
I agree with you @jacobwilliams @lockstockandbarrel, I can't see why the user runner should not apply to all tests.

**Comment by jacobwilliams** [comment]
> fpm(1) should (and did in previous versions) default to running all tests but as a work-around if you use globbing to specify all the test names or the special name ... which does not appear to be currently documented all the tests will run:
> 
> Assuming you are using the GNU/Linux time(1) command
> 
> ```shell
> #!/bin/bash
> 
> rm -f time.log 
> export TIME='%C@user@%U@system@%S@elapsed@%e@CPU@%P'
> fpm test --runner  '/bin/time --output time.log --append' '*'
> column -t -s '@' time.log|sort -k 7h |tee elapsed.log
> rm -f time.log
> 
> export TIME='%C: %Uuser %Ssystem %Eelapsed %PCPU (%Xtext+%Ddata %Mmax)k %Iinputs+%Ooutputs (%Fmajor+%Rminor)pagefaults %Wswaps'
> fpm test --runner  '2>&1 /bin/time' '*'|tee alltime.log
> ```
> 
> ### elapsed.log
> ```
> build/gfortran_E167FD2A985B468F/test/cblat1_a  user  0.00  system  0.00  elapsed  0.00  CPU  100%
> build/gfortran_E167FD2A985B468F/test/cblat1    user  0.00  system  0.00  elapsed  0.00  CPU  100%
> build/gfortran_E167FD2A985B468F/test/dblat1_a  user  0.00  system  0.00  elapsed  0.00  CPU  50%
> build/gfortran_E167FD2A985B468F/test/dblat1    user  0.00  system  0.00  elapsed  0.00  CPU  50%
> build/gfortran_E167FD2A985B468F/test/sblat1_a  user  0.00  system  0.00  elapsed  0.00  CPU  33%
> build/gfortran_E167FD2A985B468F/test/sblat1    user  0.00  system  0.00  elapsed  0.00  CPU  50%
> build/gfortran_E167FD2A985B468F/test/zblat1_a  user  0.00  system  0.00  elapsed  0.00  CPU  100%
> build/gfortran_E167FD2A985B468F/test/zblat1    user  0.00  system  0.00  elapsed  0.00  CPU  33%
> build/gfortran_E167FD2A985B468F/test/dblat2_a  user  0.05  system  0.00  elapsed  0.06  CPU  98%
> build/gfortran_E167FD2A985B468F/test/sblat2    user  0.05  system  0.00  elapsed  0.06  CPU  98%
> build/gfortran_E167FD2A985B468F/test/zblat2_a  user  0.08  system  0.00  elapsed  0.08  CPU  97%
> build/gfortran_E167FD2A985B468F/test/dblat2    user  0.08  system  0.00  elapsed  0.09  CPU  98%
> build/gfortran_E167FD2A985B468F/test/sblat2_a  user  0.08  system  0.00  elapsed  0.09  CPU  98%
> build/gfortran_E167FD2A985B468F/test/cblat2_a  user  0.10  system  0.00  elapsed  0.10  CPU  100%
> build/gfortran_E167FD2A985B468F/test/sblat3    user  0.10  system  0.00  elapsed  0.10  CPU  98%
> build/gfortran_E167FD2A985B468F/test/cblat2    user  0.11  system  0.00  elapsed  0.11  CPU  100%
> build/gfortran_E167FD2A985B468F/test/zblat2    user  0.11  system  0.00  elapsed  0.11  CPU  98%
> buid/gfortran_E167FD2A985B468F/test/dblat3_a  user  0.14  system  0.00  elapsed  0.14  CPU  98%
> build/gfortran_E167FD2A985B468F/test/sblat3_a  user  0.13  system  0.00  elapsed  0.14  CPU  98%
> build/gfortran_E167FD2A985B468F/test/dblat3    user  0.15  system  0.00  elapsed  0.16  CPU  98%
> build/gfortran_E167FD2A985B468F/test/cblat3_a  user  0.18  system  0.00  elapsed  0.18  CPU  98%
> build/gfortran_E167FD2A985B468F/test/cblat3    user  0.18  system  0.00  elapsed  0.18  CPU  98%
> build/gfortran_E167FD2A985B468F/test/zblat3    user  0.20  system  0.00  elapsed  0.20  CPU  99%
> build/gfortran_E167FD2A985B468F/test/zblat3_a  user  0.20  system  0.00  elapsed  0.21  CPU  98%
> ```
> 
> so `fpm test --runner time ...` should work in the meantime. GNU/Linux users might find the examples of sending timeing information to a separate file or including the results sequentially in stdout useful as well.

The form `fpm test --runner  'time' '*'` doesn't seem to work (at least with the latest 0.10.1 version). It seems to only run one of the tests, not all of them.

**Comment by perazz** [comment]
@jacobwilliams @lockstockandbarrel @urbanjost thanks for your comments: I think I now understand the logic and here I updated the proposed implementation: 
- No user-specified name -> dump "Available targets"
- '*' -> run all (even with --runner)
- 'name' -> run name only

The following are tests you can try from the `example_packages/many_targets` example: 

- `fpm run --example` -> dump available names
- `fpm run` -> dump available names
- `fpm test` -> dump available names
- `fpm run --example '*'` -> run all
- `fpm test '*' ` -> run all
- `fpm run '*'` -> run all
- `fpm run '*' --runner 'time' ` 
- `fpm run --exampe '*' --runner 'time' `
- `fpm test '*' --runner 'time' `

Does that consolidate/cover all the expected use cases?

**Comment by lockstockandbarrel** [comment]
fpm test   -> run all
fpm test --list  -> dump available names
fpm test --runner time  ->  run all tests with time(1) command
fpm test  test1 test2  -> run multiple tests IN ORDER SPECIFIED
fpm test  '*linear*  -> run all tests with linear in their executable name


so the difference with the test subcommand is it defaults to executing all programs while run will only automatically run programs when no names are specified when there is is only one executable. 

The other behavior that has changed between versions is whether you stop on the first executable that exits with a non-zero status. There should probably be an option to specify that explicitly but to allow for tests that stop with a non-zero status and not require them to be executed one at a time the test subcommand should probably continue. It would make for a better testing framework if it gave a tally of programs that exited with zero and those that did not.    So for all modes some kind of --noexit would be useful;   but for test --noexit could show a tally sheet at the end with the exit code of the commands and a tally of zero exits and non-zero exits.

What the defaults should be might be debatable  but it should be described under the explicit switches.

If each test program exits with zero if it passed and non-zero if it failed and they all execute by default and you get a tally for the test subcommand you have a basic test framework built into fpm(1) that promotes modularity; because it would work most naturally with a separate program for each feature by simply executing
   
       fpm test

the run and run --example subcommands should default to only running one command at a time but allow globbing to easily run multiple programs.  You might have some example programs that only run on a particular OS or particular compiler but still want some way to run them all whether they fail or not so   fpm run '*' currently exits if any app fails. That may or may not be desired

**Comment by lockstockandbarrel** [comment]
So all the subcommands should have the same options. This keeps the code simpler in that the commands are all the same eccept for what the defaults are and in describing the commands as they all have a consistent set of options and behaviors available.  Just the defaults would be different  accept the tally might only occur for test

**Comment by jacobwilliams** [comment]
I would also prefer that `fpm test` run all the tests (so the '*' is optional) since that's how it behaves now and I have CI scripts in dozens of repos that are assuming that behavior. :)

**Comment by lockstockandbarrel** [comment]
I tend to use the globbing or the ".." or "..." names to run all, but the tests should include cases using the --all switch as well.
The main issue with using "*" instead of --all is that quoting is usually required so it is generally more difficult to type but I originally allowed using .. and ... and they still work but do not appear to be documented.  so

    fpm test --all
    fpm test ..
    fpm test "*"
    fpm test

should all run all cases with or without other options such as --runner.  That is fine, but it does mean a few more unit tests should be created.
