### ISSUE TITLE
Linker flags are not parsed correctly by the command-line interface

### ISSUE THREAD

**Issue by perazz** [fortran-lang/fpm#1049]
### Description

There seems to be an issue with the fpm CLI with link flags/ general flags that involve spaces

```
fpm new blah
cd blah 
fpm run --link-flag " -framework Accelerate"
```

Returns 

```
[100%] Compiling...
ld: framework 'build/gfortran_87E2AE0597D39913/blah/app_main.f90.o' not found
collect2: error: ld returned 1 exit status
<ERROR> Compilation failed for object " blah "
<ERROR> stopping due to failed compilation
STOP 1
```

It appears that the flag is not fully parsed: on verbose, 

```
 + gfortran    -Wall -Wextra -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single -fimplicit-none -Werror=implicit-interface  -framework build/gfortran_87E2AE0597D39913/blah/app_main.f90.o build/gfortran_50F62D7499E64B65/blah/libblah.a -o build/gfortran_7B9B45E014E47138/app/blah
ld: framework 'build/gfortran_87E2AE0597D39913/blah/app_main.f90.o' not found
collect2: error: ld returned 1 exit status
```

Notice the missing "Accelerate" part: 
```
[...] -Werror=implicit-interface  -framework build/gfortran_[...]
``` 

### Expected Behaviour

Should build fine. @urbanjost do you think I'm using the CLI the wrong way here?

### Version of fpm

0.10.1

### Platform and Architecture

MacOS, homebrew

**Comment by lockstockandbarrel** [comment]
I do not see the same behavior, and adding --verbose or --usage shows the expected options on my platform. I am using Linux.
Are you using MSWindows, or what OS?  Also, I not familiar with the -framework option and it says not an option of gfortran/ifx/ifort with versions I have.


fpm new blah
cd blah 
fpm run --link-flag " -framework Accelerate"

produces urbanjs@mercury:~/github/fun/blah$ fpm run --link-flag '-framework Accelerate' --verbose
 <INFO> BUILD_NAME: build/gfortran
 <INFO> COMPILER:  gfortran
 <INFO> C COMPILER:  gcc
 <INFO> CXX COMPILER: g++
 <INFO> COMPILER OPTIONS:   -Wall -Wextra -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single
 <INFO> C COMPILER OPTIONS:  
 <INFO> CXX COMPILER OPTIONS: 
 <INFO> LINKER OPTIONS:   -framework Accelerate
 <INFO> INCLUDE DIRECTORIES:  []
[  0%]                           blah
 + gfortran    -Wall -Wextra -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single -fimplicit-none -Werror=implicit-interface  -framework Accelerate build/gfortran_87E2AE0597D39913/blah/app_main.f90.o build/gfortran_50F62D7499E64B65/blah/libblah.a -o build/gfortran_263E418A95DB4AE5/app/blah
gfortran: error: unrecognized command-line option ‘-framework’
[100%]                           blah  done.

gfortran: error: unrecognized command-line option ‘-framework’
<ERROR> Compilation failed for object " blah "
<ERROR> stopping due to failed compilation
STOP 1

**Comment by perazz** [comment]
Thank you! I'm using macOS + homebrew (which has just updated to gcc-14).
I found the issue may be with the bash script I'm using to launch fpm. 

- If I just call `fpm` with its full path: everything now runs fine!

```bash
federico@Federicos-MBP blah % ~/Documents/GitHub/fpm/bin/fpm build --link-flag " -framework Accelerate" --verbose
 <INFO> BUILD_NAME: build/gfortran
 <INFO> COMPILER:  gfortran
 <INFO> C COMPILER:  gcc
 <INFO> CXX COMPILER: g++
 <INFO> COMPILER OPTIONS:   -Wall -Wextra -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single
 <INFO> C COMPILER OPTIONS:  
 <INFO> CXX COMPILER OPTIONS: 
 <INFO> LINKER OPTIONS:    -framework Accelerate
 <INFO> INCLUDE DIRECTORIES:  []
[100%] Project compiled successfully.
```

- Instead, in my development version, I run `fpmx` from a bash script that looks like this: 

```bash
#! /bin/sh
echo $@
/Users/Federico/Documents/GitHub/fpm/bin/fpm $@
```

Now if I run `fpm` from this scipt, I get: 

```bash
federico@Federicos-MBP blah % fpmx build --link-flag " -framework Accelerate"
build --link-flag -framework Accelerate
blah                                   failed.
[100%] Compiling...
ld: framework 'build/gfortran_87E2AE0597D39913/blah/app_main.f90.o' not found
collect2: error: ld returned 1 exit status
<ERROR> Compilation failed for object " blah "
<ERROR> stopping due to failed compilation
STOP 1
federico@Federicos-MBP blah %   
```

Note that first line, that echoes the whole set of arguments that bash is passing to fpm: 
```bash
build --link-flag -framework Accelerate
```

It does include everything. So I believe something may get lost in the CLI parser because the arguments are passed to `fpm` from a bash variable, instead of directly?

**Comment by perazz** [comment]
Edit: If I double-quote `@$` in my script, everything now runs fine: 

```bash
/Users/Federico/Documents/GitHub/fpm/bin/fpm "$@"
```

So I guess the quotes ensure that the number of arguments does not change, while no-quotes means that the shell may split "-framework" and "accelerate" as two separate arguments.

**Comment by lockstockandbarrel** [comment]
#! /bin/sh
function myecho(){
echo number of arguments $#
echo one: $1
echo two: $2
}
myecho $@
myecho "$@"
exit

If you call this script with   bash FILENAME 'a b'
you will see that if you do not quote $@ you will loose the original quoting; which is a subtle behavior. It is rather nonintuitive what the difference is between $*  "$*", $@ and "$@" but basically to keep the original number of parameters you must us "$@", which it looks like you already found.  Without the quotes around $@ you are basically calling fpm inside your script just as if you
had entered:
                          fpm build --link-flag -framework Accelerate
instead of:
                           fpm build --link-flag '-framework Accelerate'
