### ISSUE TITLE
Introduce --lib to initalize a project with a library

### ISSUE THREAD

**Issue by certik** [fortran-lang/fpm#111]
Currently this is the default, but there should be an option for the default value also (in addition I propose that this should not be the default in #109).

**Comment by everythingfunctional** [comment]
I would combine this, #109, and #110 into a single issue, as these are all related.

For renaming the command line flags, I'm open to that. I tend to lean towards the more verbose to help make things more "self documenting", but understand that's not always the most popular way for everything.

In general, there are 3 (partially) independent pieces that fpm might create for a new project: `src/project.f90`, `app/main.f90`, and `test/main.f90`. Let's say the command line flags for each are `--app`, `--lib`, and `--test`.
 If I understand correctly, you're suggesting that the default should be `fpm new --app --lib name`.

In order to *not* include an app, you'd then want a `--no-app` flag. So, should we have both flags, or just the ones for the opposite of the default? Having both would imply a total of 6 flags, each of which is mutually exclusive with the other; `--app` or `--no-app`, `--lib` or `--no-lib`, and `--test` or `--no-test`. But, we only really need the flags `--no-app`, `--no-lib`, and `--test`. And then a user can't actually specify contradictory flags, because there aren't any.

Except for one question. Should we allow `fpm new --no-lib --test name`? It doesn't actually break anything, but is kind of strange, because at that point what are you going to be testing?

**Comment by certik** [comment]
Good point. In Cargo, the `--lib` and `--bin` (as Cargo calls it) are mutually exclusive, so specifying `--lib` means no `--bin`. 

Given the slight differences in Fortran and Rust and how modules are called, we can change this and figure out what makes sense for Fortran.

But the naming and default I think can be the same. "fpm new" would create the default app / executable. In addition, it can still create a library. Perhaps we'll always create a library, so perhaps `--lib` will always be on. 

As long as:
```
fpm new x
cd x
fpm run
```
works and executes the executable, then I am fine. The above I feel will be a very common workflow to test something out, whether to test out some library, or some Fortran construct, or some quick idea.

I think you start a new Fortran library much less often. Sort of like writing a Python script vs starting a new Python library that you upload on pypi. I do the script much more often.

Let's get an agreement on that first. Since you agree with the renaming of the options, those are the two main things I care about. We can discuss how exactly the `--lib` works later as we gain more experience with `fpm`.

**Comment by urbanjost** [comment]
I would prefer the default create all three, as they do not hurt anything and that you have one switch that can take the names app,test,lib that when specified only creates those elments, so the default with be
```bash
fpm new --with app,lib,test
but that if you just wanted the src/ directory as is the current default you would enter
fpm new -with lib
or that there are three switches --lib --app and --test and if any of them is specified only specified ones are generated. So the default could be whatever but as soon as you said --lib the others would only be created if listed, so
fpm new # does whatever everyone wants to be the default
fpm new -lib  # only builds src/
fpm new -lib -app -test # builds all three
I think the second is the most like other package managers.  I was thinking maybe there should just be a switch that takes a name, and there could be a name for each of the examples on the web page so you could enter something like 
```
fpm new myproject project_with_library
as  "new" (at least currently) only allows one directory name so a second name could be a "type". So something like
```
fpm new lib test src  
is another way to go

**Comment by urbanjost** [comment]
I would propose a PR that changes the **new** subcommand to the following to close #109, #110, and #111:
```textNAME
   new(1) - the fpm(1) subcommand to initialize a new project

SYNOPSIS
 fpm new NAME [--lib] [--app] [--test]

 fpm new --help|--version

DESCRIPTION
 "fpm new" creates a new programming project in a new directory.

 The "new" subcommand creates a directory with the specified
 name and runs the command "git init" in that directory and
 populates it with an example "fpm.toml" file, a src/, test/,
 and app/ directory with trivial example Fortran source files
 and a ".gitignore" file for ignoring the build/ directory
 where fpm-generated output will be placed:

    NAME/
      fpm.toml
      .gitignore
      src/
          name.f90
      app/
          main.f90
      test/
          main.f90

 Remember to update the information in the sample "fpm.toml"
 file with such information as your name and e-mail address.

OPTIONS
 NAME   the name of the project directory to create. The name
        must be a valid Fortran name composed of 1 to 63
        ASCII alphanumeric characters and underscores,
        starting with a letter.

 The default is to create all of the src/, app/, and test/
 directories. If any of the following options are specified
 then only specified subdirectories are generated:

 --lib       create directory src/ and a placeholder module
             named "NAME.f90" for use with subcommand "build".
 --app       create directory app/ and a placeholder main
             program for use with subcommand "run".
 --test      create directory test/ and a placeholder program
             for use with the subcommand "test".

 So the default is equivalent to "fpm NAME --lib --app --test".

 --help      print this help and exit
 --version   print program version information and exit

EXAMPLES
 Sample use

   fpm new myproject  # create new project directory and seed it
   cd myproject       # Enter the new directory
   # and run commands such as
   fpm build
   fpm run            # run example application program
   fpm test           # run example test program
SEE ALSO
 The fpm(1) home page at https://github.com/fortran-lang/fpm

 Registered packages are at https://fortran-lang.org/packages
```

**Comment by everythingfunctional** [comment]
@urbanjost , I like your proposal. It's simple and understandable. As a note though, `--test` would essentially be useless without `--lib` (as I noted in my prior comment), because then there's no code to test. Should `--test` imply `--lib` or should we report an error, or maybe just a warning and create the project anyway?

**Comment by urbanjost** [comment]
If you were refreshing a directory that already had src/ or app/ it could make sense.  I think if you have --test and src/ and app/ do not exist I think I would prefer a warning to an error,  but I suppose you could be in an existing package directory where the TOML file was used to create alternate directories to src/ and app/ so it might not be trivial to produce a warning only when there is no source or applications or other test directories but a warning would still be reasonable and would not have to be as rigourous as an error.  It is currently a difference between h-fpm and f-fpm that you can do "fpm new myproject --lib" and then
later do "fpm new myproject --test"  which is what I did as a new h-fpm user and got an error. This was before I knew much about how a project was even structured; as I now know I could have just done a "mkdir /tmp" and put a file in it called "main.f90" but as a first-time user I was confused; which was the motivation for making the tweek to allow the --test by itself;
but I can also see a new user doing something like "fpm --test". I have not tried that (will shortly) but I do realiize that just entering "fpm new -app" would create a test program with a missing module right now too. Maybe allowing a "refresh" wasn't as simple an idea as I thought. Mulling it a bit but a warning for both "fpm -test" and "fpm -app" when src/ does not exist seems like a minimal change needed. If "fpm -app" is done and src/ does not exist should it write a sample program with no **use** too? Never as simple as it seems.

**Comment by everythingfunctional** [comment]
Actually, I would expect `fpm new` to be an error if the folder already exists. For existing folders or fpm packages, I would expect to have commands `fpm init` or `fpm reconfigure` respectively.

Good catch on `fpm new --app`. I would expect that to create a valid project though. Probably just:

```
program project_name
  implicit none

  print *, "Hello, project_name!"
end program
```

**Comment by urbanjost** [comment]
With the current lack of the additional commands I am not sure which way to go. My personal experience is that the functionality is needed to work with an existing directory but I see the point that it might be better split but after recently reviewing some other source package managers I prefer the current simplicity of the fpm(1) interface. Maybe it is inevitable that fpm(1) bloats as well if it becomes popular but I am torn between just disabling the ability to work with an existing directory for now and letting the project evolve new commands (the lack of that functionality was vexing to me when I was first moving projects to work with fpm(1)) or just making options for "new" like --update/-reconfigure and -init/-auto and just making the default be that the directory must not exist, that a switch like --update allow for a directory to exist but otherwise act like new, and that later something like -init/-auto would search an existing directory tree using the features recently added to **build** and write a new toml file describing what it finds . Maybe that really does deserve a seperate command, and it would be hard to differntiate between tests and demos and application programs if you assumed it would just conform to what it finds (so that is why I was thinking it would write a toml file which could be reorganized but would initially just put all programs under [executable] with a blank [test] that you could easily move files. If no one wants "new" to work with existing directories I should turn it off as it would be hard to remove once people are used to it, but it would leave a hole in the functionality I consider basic. Just making the default be src/,test/,app/ would make it much less likely a new user would immediately hit the issue, I believe. That is based on the idea a new user is most likely to just enter "fpm new" and not try the switches until they got past the basics; which is only a hunch.

**Comment by urbanjost** [comment]
After trying a bunch of stuff I think **init** should be added at some point but that **new**  by default not allowing the directory to exist by default makes sense; but adding a __-backfill__ switch that says **new** does exactly what it does with an empty directory but only creates missing files is a reasonable behavior that could stay permanent would satisfy
your expected behavior but allow for **new** to work with an existing directory (conservatively not replacing existing files so it does not overwrite the README.md file you spent all night on) to provide the functionality I do not want to see missing:

```text[urbanjs@localhost fpm]$ cat x
 ffpm new A --lib
 ffpm new A --app
 ffpm new A --app --backfill
```
provides
```text
[urbanjs@localhost fpm]$ bash -x x
+ ffpm new A --lib
 + mkdir -p A
 + cd A
 + mkdir -p A/src
 + cd A;git init
Initialized empty Git repository in /home/urbanjs/venus/V600/github/f-fpm/fpm/A/.git/
+ ffpm new A --app
fpm::new<ERROR> A already exists.
        perhaps you wanted to add --backfill ?
+ ffpm new A --app --backfill
 + mkdir -p A
 + cd A
fpm::new<WARNING> A/.gitignore already exists. Not overwriting
fpm::new<WARNING> A/README.md already exists. Not overwriting
 + mkdir -p A/app
fpm::new<WARNING> A/fpm.toml already exists. Not overwriting
 + cd A;git init
Reinitialized existing Git repository in /home/urbanjs/venus/V600/github/f-fpm/fpm/A/.git/
[urbanjs@localhost fpm]$ 


```

**Comment by urbanjost** [comment]
```man
NAME
   new(1) - the fpm(1) subcommand to initialize a new project
SYNOPSIS
 fpm new NAME [--lib] [--app] [--test] [--backfill]

 fpm new --help|--version

DESCRIPTION
 "fpm new" creates a new programming project in a new directory.

 The "new" subcommand creates a directory with the specified
 name and runs the command "git init" in that directory and
 populates it with an example "fpm.toml" file, a src/, test/,
 and app/ directory with trivial example Fortran source files
 and a ".gitignore" file for ignoring the build/ directory
 where fpm-generated output will be placed:

    NAME/
      fpm.toml
      .gitignore
      src/
          name.f90
      app/
          main.f90
      test/
          main.f90

 Remember to update the information in the sample "fpm.toml"
 file with such information as your name and e-mail address.

OPTIONS
 NAME   the name of the project directory to create. The name
        must be a valid Fortran name composed of 1 to 63
        ASCII alphanumeric characters and underscores,
        starting with a letter.

 The default is to create all of the src/, app/, and test/
 directories. If any of the following options are specified
 then only specified subdirectories are generated:

 --lib       create directory src/ and a placeholder module
             named "NAME.f90" for use with subcommand "build".
 --app       create directory app/ and a placeholder main
             program for use with subcommand "run".
 --test      create directory test/ and a placeholder program
             for use with the subcommand "test".

 So the default is equivalent to "fpm NAME --lib --app --test".

 --backfill  By default the directory must not exist. If this
             option is present the directory may pre-exist and
             only subdirectories and files that do not
             already exist will be created. For example, if you
             previously entered "fpm new myname -lib" entering
             "fpm new myname -backfill" will create the missing
             app/ and test/ directories and missing programs.

 --help      print this help and exit
 --version   print program version information and exit

EXAMPLES
 Sample use

   fpm new myproject  # create new project directory and seed it
   cd myproject       # Enter the new directory
   # and run commands such as
   fpm build
   fpm run            # run example application program
   fpm test           # run example test program
SEE ALSO
 The fpm(1) home page at https://github.com/fortran-lang/fpm

 Registered packages are at https://fortran-lang.org/packages


```

**Comment by urbanjost** [comment]
perhaps an out-of-the-box feature, but the intrinsic-manages page I had has a module built by a bash shell (in .gitignore) that converts the manpage source files into a module M_intrinsics that contains all the manpage text. In my own test version of fpm I was thinking that the "fpm help" syntax versus "fpm --help" which several package managers and `git` support could have supplemental text on usage and the toml file so I added that module to test with where you can enter an intrinsic name on the help command and get a plain-text display of the man page. A copy of M_intrinisics could easily be captured to keep it up to date or a snapshot could be included; but especially since non-\*nix platforms do not have man(1) I thought I would mention it.
It also makes a good test for ANSI color sequences like in M_escape but I did not add the colorizer stuff. Essentially if the topic is not found by the help command instead of quitting it calls M_intrinsics. It allows the call to the intrinsics to be case-insensitive so if there is intrinsic called build you can still to it. "fpm help build" displays the fpm help for the build subcommand, but "fpm help BUILD" would display the intrinsic. I mention that here because I have a version that implements the changes mentioned above for review if there is no further discussion here that I could include that in trivially. I could argue myself that is overloading, but it is a feature other package managers or methods do not provide that is reasonably useful. It says on the page to "think outside of the box", right?
