### ISSUE TITLE
github dependencies are never updated

### ISSUE THREAD

**Issue by MarkWieczorek** [fortran-lang/fpm#121]
One method for downloading dependencies is to specify a github project, and optionally a specific branch, tag, or commit. However, once the entire git project is cloned, it is never updated.

An option should be provided to allow to update the dependencies when they change at github. In my opinion, if a specific tag or commit is not specified, the default behavior should in fact be to check for updates automatically.

**Comment by certik** [comment]
Actually I think we should do it like Cargo --- fpm determines a particular version that satisfies your `fpm.toml`, and generates `fpm.lock`. Then it never checks or updates any dependencies, it simply uses `fpm.lock` which has the exact dependency pinned down. But you can run `fpm update` command that will update your dependencies. More info:

https://doc.rust-lang.org/cargo/commands/cargo-update.html

**Comment by everythingfunctional** [comment]
Right now it's not doing anything to check that the version that is there is the right version, that it was cloned and checked-out correctly, etc, just that there is something there.

We haven't come up with a coherent strategy for version constraint checking, let alone version constraint solving, so I've just punted on doing anything for now. We'll probably look at what Cargo's solution was.

The solution that @certik described is what many (most?) language specific package managers have settled on. It prevents things in your code from breaking randomly because somebody pushed a bug to their repository.

**Comment by MarkWieczorek** [comment]
A related feature request is the following: Instead of cloning the entire repo, it would be useful in many instances (to speed up the download process) to only do a shallow clone (with git clone --depth=1). I'm not sure what the default beviour should be, but it would be useful to at least have the option.
