### ISSUE TITLE
TOML parser

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/fpm#149]
Part of #136 

I found 2, both support TOML v0.5 spec:

* [toml-f](https://github.com/awvwgk/toml-f) which is pure Fortran, but unfortunately GPLv3-licensed. We could ask the author to offer a more permissive license beside GPL.
* [f_tomlc99](https://github.com/gregfi/f_tomlc99) which interfaces a C parser. MIT-licensed.

So each presents an integration challenge.

**Comment by certik** [comment]
In terms of easiness of use, we should try to stick to pure Fortran packages for fpm dependencies, since the non Fortran dependencies must be built somehow on all platforms for all users, and that can get messy --- we discussed just loading such packages from Conda as binaries on all platforms, which I think is preferable, but I was hoping to integrate with Conda in the Fortran fpm, and not worry about it for haskell fpm.

As such, we can probably quite easily improve haskell fpm to be able to compile C or C++ files inside an fpm package if we have to. But 3rd party non-Fortran dependencies will cause more issues I feel.

Conclusion: We have to tackle robust building / using of non Fortran dependencies, but I would worry about it a bit later, once Fortran fpm works well. So I would just stick to pure Fortran for now.

**Comment by certik** [comment]
I asked the author of `toml-f` at https://github.com/awvwgk/toml-f/issues/1 if he would be willing to relicence. If he would, that would be awesome, I think it's exactly what we are looking for.

**Comment by LKedward** [comment]
It looks like [toml-f](https://github.com/awvwgk/toml-f) will indeed be re-licensed to dual MIT/Apache-2.0 in an upcoming PR: <https://github.com/awvwgk/toml-f/pull/2>. I notice this PR also includes an `fpm.toml` (though it relies on meson currently).
