### ISSUE TITLE
toml-f implementation produces error if more than 15 test or app programs are used

### ISSUE THREAD

**Issue by urbanjost** [fortran-lang/fpm#173]
When using the Fortran TOML interface the program issues an error message when you have more than 15 test programs or application programs in a project.

**Comment by awvwgk** [comment]
Sorry, my mistake. Already fixed upstream in `toml-f` with [`ecbc73a`](https://github.com/toml-f/toml-f/commit/ecbc73aaa78022f40d3c5fd697f204c97c992f21). Will be made available with #171 in fpm.

**Comment by urbanjost** [comment]
Great. The only other problem I had was that I added description keywords in my fpm.toml files that were being used by the registry web page and the new TOML interface rejects unknown keywords. It looks like the problem with the description and category keywords is/was being taken care of (cannot find the topic but sure it was in here somewhere) but I have mixed feelings about that. It catches typos in the file but (like NAMELIST where I also dislike that) it makes it a lot harder to mainain a single file potentially used by multiple programs that might require different data. Is that intentional?  Great work by the way. Thanks!

**Comment by awvwgk** [comment]
The new keywords came up in #165.

It was indeed intentional to have an explicit list of allowed keywords to verify the package file contains the correct entries and only the supported ones. I have to admit, I just extracted the allowed keys from the PACKAGING.md in this repository, which contains just several examples, chances were good that already supported keys would be missed and so they were.

An option would be to relax the check for allowed keys for certain sections or add a specific section that is not governed by any schema checks, see https://github.com/fortran-lang/fpm/issues/165#issuecomment-691455105. I think the schema checks are especially useful in sections like `library` or the individual `dependencies`, which influence the way fpm is building a project.
