### ISSUE TITLE
Packaging: submit fpm to MSYS2?

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fpm#401]
As an Arch Linux user I'm a huge fan of the MSYS2 packaging ecosystem for Windows and use it a lot in my GitHub actions workflows. Unfortunately, the setup-fpm and setup-msys2 action don't play well together and I usually skip the Windows testing part on fpm projects for this reason (see https://github.com/fortran-lang/setup-fpm/issues/4). The easiest solution actually might be to submit a `PKGBUILD` to the MSYS2 repository [here](https://github.com/msys2/MINGW-packages).

I worked out a simple `PKGBUILD` file for fpm following the packaging guidelines at https://www.msys2.org/wiki/Creating-Packages/.

```bash
_realname=fpm
pkgbase=mingw-w64-${_realname}
pkgname="${MINGW_PACKAGE_PREFIX}-${_realname}"
pkgver=0.1.4
pkgrel=1
arch=('any')
pkgdesc="Fortran package manager (mingw-w64)"
url="https://github.com/fortran-lang/fpm"
depends=("${MINGW_PACKAGE_PREFIX}-gcc-libs" "${MINGW_PACKAGE_PREFIX}-gcc-libgfortran")
makedepends=("${MINGW_PACKAGE_PREFIX}-gcc-fortran")
options=('strip')
license=('MIT')
source=(${_realname}-${pkgver}.f90::"https://github.com/fortran-lang/fpm/releases/download/v${pkgver}/${_realname}-${pkgver}.f90")
sha256sums=('06c139b16cf871e06cd3ea3be93c1ddbb5a94e4546a0c64822d10dc87333ac0c')
noextract=("${_realname}-${pkgver}.f90")

build() {
  cd "${srcdir}"
  local _build="build_${CARCH}"
  local _fc="${MINGW_PREFIX}/bin/gfortran"
  # Compiler flags need some tweaking
  local _fflags="-J ${_build}"

  mkdir -p "${_build}"
  ${_fc} ${_fflags} "fpm-${pkgver}.f90" -o "${_build}/fpm"
}

package() {
  cd "${srcdir}/build_${CARCH}"
  install -Dm755 fpm "${pkgdir}"${MINGW_PREFIX}/bin/fpm
}
```

What do you think, should we submit fpm to the MSYS2 project? How is the adoption of MSYS2 generally under the Windows based developers here?

**Comment by LKedward** [comment]
+1 for an MSYS2 package! Not an Arch user (yet) but I'm also a fan of the MSYS2 system. When I need to work on Windows, it's my go-to choice; it's got gcc-10, lot's of packages and I rarely run into difficulties compiling other software with it. Moreover I can distribute Windows binaries compiled in it to non-technical users. I'm not sure how many others use it since it seems most people are happy with WSL.

I haven't done much testing with *fpm* in MSYS2 since I recall some subtleties regarding filesystem access and the OS detection needs some attention (#242).

**Comment by awvwgk** [comment]
I have started a repository to package fpm myself for the MSYS2 toolchain [here](https://github.com/awvwgk/mingw-w64-fpm-pkgbuild).

This was tested extensively today by several students installing fpm for the first time on their Windows machines and we didn't saw much problems with this approach.

**Comment by LKedward** [comment]
Great to hear!

> ... I recall some subtleties regarding filesystem access and the OS detection ...

I recently pinpointed a minor issue with *fpm* on MSYS2 to be aware of which is that the wrong invocation for `mkdir` occurs in [`fpm_filesystem::mkdir`](https://github.com/fortran-lang/fpm/blob/a540c83d9e303acd6fece95927c49fa8d2565366/src/fpm_filesystem.f90#L279) because *fpm* detects generic 'Windows' but in MSYS2, `mkdir` is actually `c:\msys64\usr\bin\mkdir.exe`. This is the cause of any problems you've likely had when using parallel compilation. Fixing this contingent on proper runtime OS detection on Windows (#242).

**Comment by awvwgk** [comment]
This is now available in the MinGW repository of the MSYS2 toolchain.

**Comment by zoziha** [comment]
It looks really cool, I have been using MSYS for a long time.
I tried to install fpm, and found that msys2's fpm seems to depend on a lot of other packages that have not been involved? The size has reached 90MB?
![image](https://user-images.githubusercontent.com/32035096/132064162-8c8807ed-1daa-4e15-aa96-8381a5e677a3.png)

**Comment by awvwgk** [comment]
Maybe this is only an issue for the ucrt64 toolchain (marked as experimental in MSYS2)? How about using the standard mingw64 toolchain instead? I'm only depending on libgcc, libgfortran and git with the fpm package.

**Comment by zoziha** [comment]
Because my computer has recently changed the system, there is no mingw64 environment configured. If I enter pacman -S mingw64/mingw-w64-x86_64-fpm, it seems that other dependencies besides `gfortran`, `libgcc`, `git` are also introduced (`perl`?). This illustration may not be rigorous, but you can try your computer. 
![image](https://user-images.githubusercontent.com/32035096/132065419-2d05926b-f898-4f61-b922-8c605334fbe9.png)

**Comment by awvwgk** [comment]
Checkout the [git](https://packages.msys2.org/package/git?repo=msys&variant=x86_64) package, it depends on the perl packages you are seeing. Since git is an essential runtime dependency of fpm it will always be installed with any fpm variant.

**Comment by zoziha** [comment]
Thanks, it is indeed the case. It is my misunderstanding. 
![image](https://user-images.githubusercontent.com/32035096/132066349-a66b9d6d-7a1d-4481-b23a-49433412a44a.png)
I have been using [this version of git](https://git-scm.com/) under windows because my vs code graphical interface does not support msys2-git well.

**Comment by awvwgk** [comment]
The fpm package could have only an optional dependency on git, since git is not required for the most basic functionality. Of course we than need to provide an accurate error message from fpm in case we can't use git.

**Comment by oarcelus** [comment]
Hi, thanks for this. I love using MSYS2 aswell, I am encountering an issue however.

After running pacman -S mingw-w64-x86_64-fpm, I find that the installation is successful, but I cannot find the 'fpm' executable anywhere in my system. It is definitely not included in the /usr/bin/ path as the rest of the packages that I try to install.

**Comment by oarcelus** [comment]
I am using the default one after installing msys, so MinTTy I believe

**Comment by awvwgk** [comment]
I would assume the default terminal means the `msys` one for you, which is the least functional terminal available.

You have a couple of terminals available: `msys`, `mingw32`, `mingw64`, `ucrt64`, `clang32`, and `clang64`. You have start the terminal you installed `mingw-w64-<arch>-fpm` for, where `<arch>` is either `i686` (`mingw32`), `x86_64` (`mingw64`) or `ucrt-x86_64` (`ucrt64`).

**Comment by zoziha** [comment]
Or you **manually** check the path where your `fpm.exe` is installed, maybe `C:\msys64\mingw64\bin\fpm.exe`, then add `C:\msys64\mingw64\bin` to the environment path, so that you can use it in CMD/Powershell/Bash/Fish ..
