### ISSUE TITLE
fpm(1) should produce a message not stop when it cannot find the source for a module

### ISSUE THREAD

**Issue by urbanjost** [fortran-lang/fpm#405]
fpm should produce a warning or an informative message not an error when it 
cannot find the source for a module. If I want to use OpenMP with gfortran
and enter

```bash
fpm build --flag -fopenmp
Unable to find source for module dependency: "omp_lib" used by "app/main.f90"
ERROR STOP 1
```
when using the -fopenmp switch with gfortran I should be able to use the OMP_LIB
module. The same thing happens if I want to use system-installed modules that I
can point to via environment variables or -I,-l,-L, ...

So something as simple as this cannot be compiled ...
```fortran
program matrix1
    use omp_lib
    implicit none
    integer :: n, nthreads
    real(kind=8), allocatable, dimension(:,:) :: a,b,c
    integer :: i,j,k

    ! Specify number of threads to use:
    !$ print *, "Using OpenMP, how many threads? "
    !$ read *, nthreads 
    !$ call omp_set_num_threads(nthreads)
      :
      :
      :
```

**Comment by jacobwilliams** [comment]
Yep, same thing happens with the build in intel modules (ifport, ifcore, etc.)

**Comment by awvwgk** [comment]
One could guard the import of the `omp_lib` with
```
!$ use omp_lib
```
to mitigate the issue.

---

There are plenty of other external Fortran modules, which won't enter the fpm ecosystem any time soon, we should look for a more general mechanism to allow declaring external modules in the package manifest. Maybe similar to `build.link` a `build.use` or `build.module` entry could declare external modules required by the project. Those cannot be provided by the project or its depednencies and must be provided externally.

**Comment by urbanjost** [comment]
Yes. Forgot to mention that is with I did with omp_lib is prefixed it with !$. That works fine.  I also think it would be good to be able to specify external modules but I still think it should only be a warning and that actually listing it would remove the warning.  I have not looked but thought that might be straight-forward.  Is there a down-side to making it a warning that outweighs the issues that it causes by being present?  Modules are becoming more commonly used for everything from MPI to OpenMP to vendor compiler extensions to locally developed interfaces and it would be hard for anything but the compiler and loader to determine if they are actually available or not.  If they were even ignored silently except by the compiler/loader I think I would prefer that.

**Comment by LKedward** [comment]
To answer your question, there is no fundamental reason why we can't make it a warning instead, but I also like Sebastian's example for a manifest syntax which is more what I had in mind for using external modules __while it is still necessary__.

IMO Fortran developers need to move away from trying to install system-wide module libraries, since it simply isn't supported in a general way (see #71,#257&[fortranwiki](http://fortranwiki.org/fortran/show/Library+distribution)) and this is a problem that *fpm* solves directly. In the short term and in the first instance we can quite easily develop *fpm* packages that provide module interfaces to such system-installed libraries instead of relying on `.mod` files.
