### ISSUE TITLE
Establishing a release schedule

### ISSUE THREAD

**Issue by rouson** [fortran-lang/fpm#416]
Assuming the default branch is always releasable, i.e., has no regressions, would it make sense to establish a regular release schedule?   Are the most time-consuming aspects of the release process automated so that this request is not burdensome?  If so, then I would recommend releasing every 2-3 weeks.

**Comment by awvwgk** [comment]
I'm actually quite happy with the current flexible release strategy. At the current pace we get enough features / fixes together to roll out a release every month, which is nice since we are also making much progress with fpm. Still, I won't feel obliged to release for two months or longer if everybody here is busy elsewhere.

The easiest solution we can implement is a continuous release which always provides binaries from the latest head. Which I did for some of my projects already after my user base started to press me for more frequent releases.
