### ISSUE TITLE
Caching `fpm` version

### ISSUE THREAD

**Issue by HaoZeke** [fortran-lang/fpm#473]
Currently the `cache.toml` file does not include the version of `fpm` used to generate it; unless `fpm` is specified as a dependency in the `fpm.toml` file. This seems a little counter-intuitive; and it might make sense for the `cache.toml` file to include the `fpm` version used by default.

**Comment by awvwgk** [comment]
I like the idea, but I don't see how fpm could make use of this information right now. If fpm 0.3.0 changes the `cache.toml` format and receives a `cache.toml` generated from fpm 0.2.0 it would probably invalidate the cache automatically and regenerate it rather than migrating it internally to the new format right now. Migrating from a version to another requires to keep a track of the schema changes in fpm in some way (it's possible with toml-f, but maybe not worth the effort as long as `cache.toml` is a build artifact rather than an actual lock file).

Instead we should think about versioning the dependency lock file format once we implement it.

**Comment by HaoZeke** [comment]
Ah that makes sense. I was under the impression that the `cache.toml` was meant to be the dependency lock file; will close this and keep an eye out for the discussion about the lock file format!

**Comment by awvwgk** [comment]
See https://github.com/fortran-lang/fpm/issues/320
