### ISSUE TITLE
Space in the name section

### ISSUE THREAD

**Issue by han190** [fortran-lang/fpm#503]
Hi, thanks for this great tool. I tried fpm on my toy project yesterday and it all went well! But it took me a while to figure out that spaces are not allowed in the name section. I've never used `.toml` before so bear with me! The issue is, for example,
```toml
name = "Hello-World"
```
is fine but 
```toml
name = "Hello World"
```
will create one folder named `Hello` in the build directory and another folder named `World` in the repository root directory. So would you please add a sentence to mention that space is not allowed in the name section in [PACKAGING.md](https://github.com/fortran-lang/fpm/blob/master/PACKAGING.md)?

Thanks again for this great tool!

**Comment by awvwgk** [comment]
Thanks for the report. I think this is a bug in the way directories are created, a space in the package name should be allowed.

**Comment by urbanjost** [comment]
There was a conscious decision to limit the name to what is allowed for a Fortran variable name early on; which has since been extended to allow an ANSI dash character as well.  If you entered "fpm new 'one two'" it would cause an error; but there is no revalidation check of the fpm.toml file.  Spaces and many other characters in names are very problematic in command line environments and the name used in the fpm.toml file may be or is involved in the generation of file names. In this case when the
command  "mkdir build/NNNN_a b c"  is run to make the scratch directory with requoting it goes through the execute command which calls a shell and does shell expansion, ending with three directories being generated. There are a lot of issues like that, not just with the  name in the fpm.toml file if special characters are in names.  The "new" subcommand already checks the name and the original request was just to  this.  I think an additional simple check when reading the fpm.toml file and adding some more documentation would be better.

**Comment by awvwgk** [comment]
This should be fixed with #511 now.
