### ISSUE TITLE
Automatically create gitignore for build artifacts

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fpm#525]
Build systems like meson put a `.gitignore` in the build directory to avoid accidentally committing in the repository.

```
# This file is autogenerated by Meson. If you change or delete it, it won't be recreated.
*
```

Fpm could also put a `.gitignore` in the `build` directory with just `*` to avoid committing any build artifacts.

**Comment by urbanjost** [comment]
An fpm `new` subcommand makes a .gitignore with the line 'build/*' in it, but I do like your suggestion.  I think in that case the gitignore in the build/ directory makes perfect sense, as everything in there is generated by fpm. The only hesitation might be that if someone is using git(1) for more than just generating a standard fpm directory, they might actually WANT to push or pull the entire directory, perhaps to a mirror in their own organization, for example. Perhaps only making it when the build/ directory is created is OK, and not checking for it at each execution (which I think is what you were suggesting anyway) is OK, especially since not everyone initializes a package with `new` but just creates it manually or some other way; but I would like a line mentioning that somewhere in the user guide mentioning you need to delete it in that case.  I think it is desirable such a high percentage of the time that it does not need a .command switch on `fpm` itself.  Would we then get rid of the one generated in the top of the package currently by new?  I think I would, as it would be redundant and could just lead to confusion and it is neater if everything generated by `fpm` is in the build directory whenever possible.
