### ISSUE TITLE
get author and email using git config for fpm.toml

### ISSUE THREAD

**Issue by freevryheid** [fortran-lang/fpm#650]
### Description

The defaults added (Jane Doe) require editing post fpm new. Why not automate using git config?

### Possible Solution

use git config --get user.name for author  & copyright in fpm.toml
use git config --get user.email for maintainer in fpm.toml
use defaults if above returns blank

**Comment by freevryheid** [comment]
created pull request:
https://github.com/fortran-lang/fpm/pull/652

**Comment by urbanjost** [comment]
I like the idea, it goes back to at least #127, but as discussed in #316, an alternative might be for fpm to have it's own .fpmconfig and use TOML since it is already part of fpm, which would use already existing code and not need an external process; not all users are .git users and might not even use any code version control or might use an alternative like hg(1);  but I think that can wait and if that does occur it could look in both .fpmconfig and .gitconfig.  I would like a .fpmconfig that was "standard" as .gitconfig is sort-of INI but not really any standard other than specifically being a git(1) config file; and that would allow users to have things like a default preferred compiler or any other values we wanted, like a default directory for the install(1) subcommand, etc. 

Note if you do not have external dependencies you can use fpm(1) without git. That being said I think so far the vast majority of fpm(1) users are using git(1) or at least have installed it so fpm(1) dependencies work (?). I just saw this and that I was flagged for review; hope to look at it tonight or tomorrow in more depth. Have not looked at code, but if it using system-specific methods to see if git is in the command path, there is a which(3f) routine in fpm (or maybe just an fpm PR, will check) that might be useful.  Definitely time to get rid of the "Jane Doe" default when probably more than 9 out of 10 users have this in their .gitconfig.
