### ISSUE TITLE
Error while running tests in new-test directory

### ISSUE THREAD

**Issue by arteevraina** [fortran-lang/fpm#678]
### Description

I am currently playing around with fpm repo and I noticed a bug. When you run `fpm test new-test` command in terminal it will pop up an error message like this.
![Screenshot from 2022-03-15 20-37-14](https://user-images.githubusercontent.com/43968121/158409651-ee9bff14-8ec2-47e1-860d-fdad0a0a5b84.png)

I suppose that this might be coming because fpm new command that is run in test requires a directory name as well that may be missing while executing the command in test. 

### Expected Behaviour

This message should not come up. As user of fpm will get confused if all the tests are passing then why is the error coming up.

### Version of fpm

0.5.0 , alpha

### Platform and Architecture

Ubuntu 20.04

**Comment by ivan-pi** [comment]
I think you are confusing the output message from the [`new_test.f90`](https://github.com/fortran-lang/fpm/blob/main/test/new_test/new_test.f90) driver with a genuine error. The driver aims to test different variations of the `new` subcommand. 

The output you see comes from running this string as the input command:
https://github.com/fortran-lang/fpm/blob/86a8e2f71ee16be30bc21b7ff0273de324a59985/test/new_test/new_test.f90#L16

Here's how to get the same output directly:
```text
ivan@maxwell:~/Documents/fpm$ fpm new
       <USAGE> fpm new NAME [[--lib|--src] [--app] [--test] [--example]]|[--full|--bare] [--backfill]

<ERROR>directory name required
STOP 1
```

Arguably, we could do with a better error message. As I understand it, the message "directory name required" is referring to the missing `NAME` argument expected by the command.

Concerning the expected behavior, this will only be confusing for fpm developers who actually bother to run the fpm tests. But indeed the output

**Comment by arteevraina** [comment]
Sure, got it. This is the actual behaviour of the command. Looks good :)
