### ISSUE TITLE
`fpm` fails to compile projects in parallel: Fortran runtime error: File cannot be deleted

### ISSUE THREAD

**Issue by zoziha** [fortran-lang/fpm#707]
### Description

Since the `.rsp` file is used when the link library `.a` file is generated, **the generation and deletion** of the `.rsp` file should not be performed in multiple threads.

```sh
>> cd fpm && fpm install --prfile release --flag "-fopenmp "
>> fpm build
... 
fpm.f90                                done.
install.f90                            done.
libfpm.a                               compiling...
main.f90                               compiling...
[ 50%] Compiling...At line 688 of file .\src\fpm_filesystem.F90
Fortran runtime error: File cannot be deleted

Error termination. Backtrace:

Could not print backtrace: libbacktrace could not find executable to open
#0  0xd3e2965a
#1  0xd3db0181
#2  0xd3cd475b
#3  0xd3d97173
#4  0xb51f705e
#5  0xb51f1cd3
#6  0xb51c9b6d
#7  0xb51ca21d
#8  0x849fcb7
#9  0x12044b4a
#10  0x3ea51bb1
#11  0x40467033
#12  0x410a2650
#13  0xffffffff
```

### Expected Behaviour

`fpm` build successfully.

### Version of fpm

0.5.0

### Platform and Architecture

Windows 10, msys2-ucrt64-gfortran 12.1.0

### Additional Information

This is the first time I know that `fpm` supports parallel builds, and I think it's great for larger projects, why don't we add a parallel version of the `fpm` executable to the distribution?

**Comment by LKedward** [comment]
Thanks for opening an issue for this @zoziha. I also encounter this sporadically on msys2, but haven't had the time to figure it out.

> ... why don't we add a parallel version of the `fpm` executable to the distribution?

The executables built in the CI are statically linked for portability and my understanding is that it isn't recommended to statically link threaded applications due to nuances with how local thread implementations like pthread work. I don't fully understand the issues, however I haven't been successful in statically linking an OpenMP executable and using it on different systems.

The exception to this is on Windows, where statically linked OpenMP executables produced via mingw_w64 seem fine to distribute to other Windows machines due to their uniformity. We could therefore update the CI flags for Windows to build with OpenMP (I already do this with my [Quickstart Fortran](https://github.com/LKedward/quickstart-fortran) installer)

**Comment by zoziha** [comment]
```sh
>> fpm run --profile release --flag "-fopenmp -static" --runner ldd
Project is up to date
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7ffc41050000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7ffc40450000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7ffc3e760000)
        ucrtbase.dll => /c/WINDOWS/System32/ucrtbase.dll (0x7ffc3ea30000)
```
On Msys2-gfortran, it does look exactly like you said.
