### ISSUE TITLE
segfaults with invalid dependency

### ISSUE THREAD

**Issue by freevryheid** [fortran-lang/fpm#724]
### Description

I changed a git dependency to a path as follows:
``` toml
[dependencies]
vecfun.git·=·{·path·=·"../../vecfun"·}
```

fpm build segfaulted - then figured to change the dependency, deleting the .git 
``` toml
[dependencies]
vecfun·=·{·path·=·"../../vecfun"·}
```

### Expected Behaviour

A hint with regards invalid dependency?

### Version of fpm

0.6.0, alpha

### Platform and Architecture

Linux

**Comment by awvwgk** [comment]
The value of the *git* subtable is fetched here:

https://github.com/fortran-lang/fpm/blob/3045817f6b0301e68cdc4f51381f789edcd0c43f/src/fpm/manifest/dependency.f90#L82

*url* will be unallocated in case the of a type-mismatch, like providing a table instead of a string. However we don't check this case and call the constructor later which expects `character(*), intent(in)`.
