### ISSUE TITLE
cmake_minimum_required => 3.14

### ISSUE THREAD

**Issue by scivision** [fortran-lang/fpm#8]
https://github.com/fortran-lang/fpm/blob/bf8ee015890da9528572b9dbc8eeaa4dd57e132c/src/main.rs#L38

The CMake syntax used in this Rust script requires at least CMake 3.13.
 In general in the Fortran stdlib we currently planned to use CMake 3.14 minimum.

**Comment by certik** [comment]
Yes, it needs to be 3.14. Is the `FATAL_ERROR` needed? It seems to fail fatally even without it.

**Comment by milancurcic** [comment]
This raises a broader issue about how should we handle minimum CMake version in fpm. 

Should we set a fixed minimum cmake version for all packages brought in by fpm (even if they are okay with an earlier version)? This seems like an unnecessary overkill to me.

Or, should we let cmake do the work and have individual package builds fail if user's cmake is inadequate? I like this better.

Are there other approaches?

**Comment by scivision** [comment]
if you intend to communicate with CMake beyond simple command line interaction, there was a significant improvement in CMake 3.14 adding a [file based API](https://cmake.org/cmake/help/v3.14/release/3.14.html#file-based-api). That would avoid having to implement that twice for CMake < 3.14 and the deprecated CMake server, if such communication is necessary for fpm.

This would allow for example to introspect CMake projects that don't use fpm, but are used by fpm.

**Comment by scivision** [comment]
In my opinion the `FATAL_ERROR` parameter to `cmake_minimum_version()` can be omitted. It does nothing for CMake releases less than about 15 years old, and those with CMake that old would have trouble building almost anything for the past few years.

**Comment by certik** [comment]
@scivision thanks. (I can't believe I've been using CMake longer than 15 years, but it seems I have...)

Regarding the minimal version, it requires 3.14 for Windows, and I was thinking of simply using that for now everywhere.

Once `fpm` is further along, let's revisit this. Down the road I actually think `fpm` should be able to build things on its own, just like Cargo does it, which would be a lot faster (since cmake's configure phase can be pretty slow).

For now I just want to get some minimal product working, then we'll carefully revisit all these decisions.

**Comment by awvwgk** [comment]
This seems to be related to the removed Rust version.

The minimal required CMake version will become relevant again, once we implement a CMake generator. Once this becomes relevant we can either reopen this issue or create a new one.
