### ISSUE TITLE
Fails to run tests after a package is built: Fortran runtime error: EXECUTE_COMMAND_LINE: Invalid command line

### ISSUE THREAD

**Issue by barracuda156** [fortran-lang/fpm#830]
### Description

Sorry, I am new here, maybe it is something obvious, but I do not know why this fails:
```
--->  Building finterp
xinstall: mkdir /opt/local/var/macports/build/_opt_PPCRosettaPorts_math_finterp/finterp/work/bin
Executing:  cd "/opt/local/var/macports/build/_opt_PPCRosettaPorts_math_finterp/finterp/work/finterp-1.3.0" && /opt/local/bin/fpm build --flag -DREAL32 
 + mkdir -p build/dependencies
[  0%] linear_interpolation_module.F9
[ 50%] linear_interpolation_module.F9  done.
[ 50%]                   libfinterp.a
[100%]                   libfinterp.a  done.
[100%] Project compiled successfully.
--->  Testing finterp
Executing:  cd "/opt/local/var/macports/build/_opt_PPCRosettaPorts_math_finterp/finterp/work/finterp-1.3.0" && /opt/local/bin/fpm test 
[  0%] linear_interpolation_module.F9
Fortran runtime error: EXECUTE_COMMAND_LINE: Invalid command line

Error termination. Backtrace:
Command failed:  cd "/opt/local/var/macports/build/_opt_PPCRosettaPorts_math_finterp/finterp/work/finterp-1.3.0" && /opt/local/bin/fpm test 
Exit code: 2
Error: Failed to test finterp: command execution failed
```
I have tried with a couple of packages: they build and install fine, but tests fail to run. How to fix this?

### Expected Behaviour

`/opt/local/bin/fpm test` should work as supposed to.

### Version of fpm

0.7.0

### Platform and Architecture

macOS 10.6.8/ppc

### Additional Information

gcc 12.2.0

**Comment by urbanjost** [comment]
The run subroutine should get the message from execute_command_line and echo the message from the system, as it likely contains a useful message.  It looks like you did not add the "--flag -DREAL32  --verbose" option on the test command, so it was building the executable again, as that would result in a different executable. It should shown an error message at that point as it looks like the build failed. It then proceeded to try to execute the command and the command file very likely does not exist, so the system command failed.  I will try to duplicate that because I would have expected it to end when the build failed and to have produced a message. If the message were produced it probably would have said "command not found".  It is unusual that you are using the full pathname to fpm instead of having it in your path, but that is probably not a problem.  If the "fpm test --flag -DREAL32 --verbose"  command fails it should show the actual system command being executed with a "+" in front of it. Execute that command manually and see what error it produces.

**Comment by barracuda156** [comment]
@urbanjost Thank you for replying!

I have fixed tests implementation a day ago: https://github.com/macports/macports-ports/commit/37515e43a3ab0eecfd2fca33ce68491885da35d2

So this issue is solved. I think the problem was that it was not finding gfortran since it was passed in build env but not test env.

BTW those flag for size of real are generally applicable to any package built via FPM? If yes, I will add them as variants in the portgroup.

**Comment by urbanjost** [comment]
Each different set of flags creates a separate  executable in the build directory.  The test command will do a build by itself if it does not see a matching binary (that is, you can just do "run test" instead of "run build;run test" and get the same result.   So in your commands you showed in the log file you were saying "--flag -DREAL32"; but you were not saying that on the test run, so as shows in the log file the test build was trying to build a new version to test.

[  0%] linear_interpolation_module.F9

but then it stops with no error message but it should have kept building till it got to 1  00%, just like in the first build. If you are creating environments for each and the compiler was not there it would make sense it failed.  So -DREAL32 is not a standard switch, it just has to match in each command or a new binary is built.  The --verbose switch is a standard fpm option.  The -DREAL32 switch is saying to define the variable REAL32 for use with the cpp/fpp pre-processor; and could generally be any name. I was only saying to repeat it because you had used it.

So it is good you have a fix, so you should probably close this;  but I think I will submit a small patch to always echo the system error message when calling external commands. It probably would have been easier for you if it had said "gfortran command not found"  instead of just saying "ERROR".

**Comment by barracuda156** [comment]
Yes, I will add --verbose to build options, that makes sense. I did not pass -DREAL32 from my end though, it was apparently picked by a build system of FPM. From what I understand, we can still use -DREAL64 on 32-bit platforms, and it seems to work fine and pass tests.

**Comment by urbanjost** [comment]
I added a push request that should generate more useful messages for the next person.  Still confused where the -DREAL32 is coming from on the build command, as the fpm(1) code itself does not contain that string, but I am not exactly sure what building tools or environment you are using  (I have not worked with MACport directly); but it looks like you have worked through everything.  If possible, you want to capture or redirect stderr as well, because I suspect there were some messages there that got lost (at least on a Linux box a backtrace is generated, although it is not particularlyand  clear it does at least indicate a failure occurred and maybe made diagnosing the problem easeri.
