### ISSUE TITLE
Use the exit code of the program as the exit code of fpm

### ISSUE THREAD

**Issue by Carltoffel** [fortran-lang/fpm#848]
### Description

When running a program with fpm, would it be possible/useful to hand over the exit code of the program back to the shell? Currently, if the exit code of the program is `/=0` fpm will exit with the code `1`.  Thus, information about the error isn't accessible from the shell.
Are there any reserved error codes which cannot be used?

### Possible Solution

Use the exit code from the executable as the exit code of fpm

**Comment by perazz** [comment]
fpm doesn't have an exit error codes system and I very much like the idea. 
That said, several reasons for non-zero exit codes would be possible when trying to run a program, besides returning the error code from the program itself, so, we should think of a smart enough way to do this.

**Comment by urbanjost** [comment]
That seems like an intuitive feature, and EXECUTE_COMMAND_LINE has CMDSTAT to return errors specific to it, but also has EXITSTAT, which should have the exit status code you suggest on systems that support exit codes; so it should be very easy to do what you suggest, if I am understanding it properly.

**Comment by urbanjost** [comment]
The main reason originally to have an fpm_stop and run procedure was to be able to control the exit gracefully, and to color messages  (strings like <ERROR> were to be optionally converted to color or monochrome via a simplified version of M_escape,which was supposed to handle processing all messages); somewhere along the line there are calls to cmd_run, run, and execute_command_line, a,nd other changes that have drifted away from that. Error messages were supposed to all go to stderr, and a -quiet and -verbose switch were supposed to give control over the messages but originally there was some effort to keep it as simple as possible, and quiet a few independent parallel features were being developed which made that a low priority. It would be nice to go back and formally structure that.  The other possibility was that by letting all messages go through routines like fpm_stop that multi-lingual options could be supported as well. So that is why there are some parts at least partially in place, like fpm_stop().  It would be nice to go back and clean that all up.  Should an independent package be developed that other projects can use as well that can be used like the TOML and M_CLI2 modules, or something smaller just for fpm(1)?

**Comment by perazz** [comment]
I'm all in on this but I think we need to establish what is better: 

1) A simpler solution, i.e., just pass the error code from `execute_command_line` to `fpm_stop` like you're suggesting. This is fine, but it could hinder more expressive fpm error codes in the future, because they could always collide

2) Return a standardized `fpm` error code, like
```fortran
integer, parameter :: FPM_OK = 0
integer, parameter :: FPM_RUN_ERROR = -1

[...]
call fpm_stop(FPM_RUN_ERROR,'*cmd_run*:stopping due to failed execution: stat='//to_ascii(lasterror))
```

the parent's program error code would still be very easy to catch (`grep FPM_RUN_ERROR <stderr>`), and, fpm would always return a standardized error code which can safely be used for fpm to interact with other programs.

I would lean toward option 2, it looks more robust for the long term?

**Comment by Carltoffel** [comment]
I just found [this exit code guide](https://tldp.org/LDP/abs/html/exitcodes.html). Maybe someone knows something similar for Windows.

We can have both options suggested by @perazz
The only thing we have to do is to reserve some error codes, e.g. < 10:
- If there was a fpm dependencies/compile/link error, it will return 3, 4, 5... etc. 
- If a program returns something in this range, `fpm` returns 1.
- And if the program returns something >= 10 this code will be passed to the command line.

**Comment by perazz** [comment]
Yeah I understand that returning a single error code would be easier, but I'm not sure if I'm in favor of defining arbitrary rules like (`stat>=10`). Perhaps one simpler way to do it was to define: 

- all fpm errors have negative codes 
- successful return returns 0
- positive codes mean "abs(code) returned from `execute_command_line`"

But again, command line execution may return anything (command not found, etc.), not necessarily the application's return code. How would we differentiate between them? The more I think about this the more I like option 2: fpm could return a `FPM_COMMAND_NOT_FOUND` for example in that case

**Comment by Carltoffel** [comment]
Negative exit codes will cause problems because on Linux, an exit code is only one byte which represents numbers from 0-255.

What do you mean when you say "command line execution may return anything"? You can catch and fix/translate all exit codes that happen while fpm is running.

We could even say, fpm returns some specific exit codes for building/linking/etc errors and if the user needs the exit codes of the Fortran executable, they have to execute it in a separate line. But IMHO, it would be better to define a range in which the programmer of a fpm project can define exit codes.

**Comment by perazz** [comment]
> What do you mean when you say "command line execution may return anything"?
@Carltoffel I was meaning that if my command is to run a program, the error code may be the one returned from the program, or a system one (in case of CTRL+C, file not found, etc.). Needless to say system codes are very platform dependent (i.e. mostly negative IDs in Windows).

I've done a bit of internet searching and the solutions vary wildly. I think for fpm, the two most reasonable options seem to be: 
- Just reserve some values like you're suggesting (i.e., [node.js](https://www.geeksforgeeks.org/node-js-exit-codes/) does this, with the perk that they use the 128+ range knowing that it fallsback to 0+ range in Unix; also [python](https://docs.python.org/3/library/sys.html#sys.exit) is neutral, though it recommends to use values between 0-127 too)
- We could do what @urbanjost suggests, i.e., write a tiny platform-independent library. I couldn't find much to take inspiration from out there, maybe one could start from the [gnu C library](https://www.gnu.org/software/libc/manual/html_node/Error-Codes.html) and find equivalents on other platforms?

**Comment by perazz** [comment]
See #852: I think @urbanjost's suggestion is the straightforward way of introducing this. Maybe down the road it can be expanded. @Carltoffel how do we test this?

**Comment by urbanjost** [comment]
"fpm new testit" and make a main.f90 that looks like this would be a start. Since the STOP statement on most machines (annoyingly to me) prints the exit status it should let you visually see it is correct. In the tests for fpm on the Linux tests they run in a bash shell so you can test $? or $status in the CD/CI scripts running something similiar.

```fortran
program main
implicit none
character(len=20) :: string
integer           :: istop

  string=''
  call get_command_argument(1,string)
  if(string.eq.'')string='0'
  read(string,'(i20)')istop
  stop istop
end program main
```
```bash
fpm run -- 100
fpm run -- 256
fpm run -- 257
fpm run -- -100
```
# most linux systems so a modulo on 256, I believe; so only eight unsigned bits are significant and some systems might still be around doing a modulo on 128. If I remember write UNIX originally only used 0 through 31; so the tests on different platforms might be interesting; but as far as I know any reasonably recent Linux supports one byte.

I was pondering if fpm(1) should only return it's own exit values for all fpm commands unless a flag was used. Cumbersome but returning the exit code from the executable run is really just a development feature, as when a program is installed somewhere what fpm(1) does or does not do does not matter.  Maybe only return the exit code of the program being executed if the -- option is present, although that is cryptic; or add a  --userexit. I think that programs are rarely used in production via an fpm(1) command.

I am using the feature and like it myself in a branch of fpm as I have some scripts that run my tests for QA; and I already find this handy in CD/CI scripts that are running  "fpm test"; but I would not find it too inconvenient if a switch were requred.

**Comment by perazz** [comment]
Thank you @urbanjost @Carltoffel: I think the base feature is complete! 

The test is a simple program that checks that the command argument is an odd integer, and returns 0 on success or a few error codes otherwise: 

https://github.com/perazz/fpm/blob/1133a03f8967caf77e2b6804154ad61c126325fe/example_packages/fpm_test_exit_code/app/main.f90#L7-L42

The CI now tests all of them like @urbanjost suggested: 

https://github.com/perazz/fpm/blob/1133a03f8967caf77e2b6804154ad61c126325fe/ci/run_tests.sh#L161-L195

**Comment by perazz** [comment]
Looks definitely closed for now, I will close this issue.
