### ISSUE TITLE
Is usage of ieee_arithmetic strictly necessary here?

### ISSUE THREAD

**Issue by barracuda156** [fortran-lang/fpm#882]
### Description

ieee_arithmetic is not universally supported in Fortran. If it can be avoided without losing functionality, it is desirable.
```
fpm.F90:11872:21:

11872 |    use, intrinsic :: ieee_arithmetic, only : ieee_value, &
      |                     1
Fatal Error: Cannot find an intrinsic module named 'ieee_arithmetic' at (1)
```
P. S. I have experimental fix for `gfortran`, but a) it may take forever until it gets merged in GCC and b) some other platforms have none.

### Expected Behaviour

As long as ieee_arithmetic is optional, better make it conditional or avoid altogether. (Of course, as long as functionality is not compromised: fixes for one platform should not break anything for someone else.)

### Version of fpm

0.8.1

### Platform and Architecture

macOS 10.6.8/ppc

**Comment by awvwgk** [comment]
There is no usage of `ieee_arithmetic` in the fpm code base, rather this issue is related to the lexer in TOML Fortran (see [`src/tomlf/de/lexer.f90#L1297-L1309`](https://github.com/toml-f/toml-f/blob/6290b0bc5f5ebeff231625a3b6685de85f33fc79/src/tomlf/de/lexer.f90#L1297-L1309)). Feel free to open an issue at https://github.com/toml-f/toml-f regarding usage of `ieee_arithmetic`.
