### ISSUE TITLE
Build fails with clang on MacOS

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fpm#907]
### Description

Building fpm for conda-forge results in the following error:

```

././src/fpm_os.c:12:10: error: incompatible pointer to integer conversion returning 'char *' from a function with result type 'int' [-Wint-conversion]
  return realpath(path, resolved_path);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
<ERROR> Compilation failed for object " src_fpm_os.c.o "
<ERROR> stopping due to failed compilation
STOP 1
```

### Expected Behaviour

Using clang on MacOS as C compiler should work as expected

### Version of fpm

0.8.2

### Platform and Architecture

MacOS/x86_64

### Additional Information

See https://github.com/conda-forge/fpm-feedstock/pull/18

**Comment by perazz** [comment]
I believe it happens because the interface is incompatible: 

https://github.com/fortran-lang/fpm/blob/87bec7f63feac3d187a4ea6d92f3279251cf1cde/src/fpm_os.c#L8

should return a `char*`. I had fixed it [here](https://github.com/perazz/fpm/commit/07fae7cd0ef035b35f6f9fb69196f0aebe91b527#diff-63f8d8b934931061f86ff4ce7a18a550366346c22b9a442c4500fd74b7b3823d), @minhqdao this should be an easy one, can I ask you to take care of it?

**Comment by barracuda156** [comment]
@awvwgk 0.8.2 built fine with Clang on macOS 13 for us: https://github.com/macports/macports-ports/actions/runs/4957808218/jobs/8869925080?pr=18637

However since 0.8.x there is another weird problem: often download fails, like here:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   280  100   280    0     0   1404      0 --:--:-- --:--:-- --:--:--  1465
Could not fetch the latest release from GitHub. Install curl or wget, and ensure network connectivity.
```
https://build.macports.org/builders/ports-10.15_x86_64-builder/builds/136455/steps/install-port/logs/stdio

Something is broken with this.
