### ISSUE TITLE
Failing CI: (macOS) Install homebrew OpenMPI

### ISSUE THREAD

**Issue by minhqdao** [fortran-lang/fpm#939]
### Description

The CI fails while trying to install OpenMPI on macOS via homebrew.

It also takes forever (47m 36s until failure).

https://github.com/fortran-lang/fpm/actions/runs/5271571352/jobs/9532646356?pr=937

@perazz 

### Expected Behaviour

It doesn't fail.

It's done super quickly.

### Version of fpm

The one used in the CI

### Platform and Architecture

macOS

**Comment by perazz** [comment]
To maintain C++ support, homebrew-OpenMPI needs to be [built with g++](https://stackoverflow.com/questions/27930481/how-to-build-openmpi-with-homebrew-and-gcc-4-9) instead of clang++. 
This takes a long time. As this step is not cached yet, @minhqdao, can I ask you to please check investigate a strategy to cache the homebrew-OpenMPI action?
